project_id = "nplznqgzotuhzscwcrui"

[functions.create-payment]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.poll-video-status]
verify_jwt = false

[functions.generate-runway-prompt]
verify_jwt = false

[functions.generate-runway-video]
verify_jwt = true

[functions.check-runway-status]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

