project_id = "nplznqgzotuhzscwcrui"

[functions.create-payment]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.poll-video-status]
verify_jwt = false

[functions.generate-veo3-prompt]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.free-trial]
verify_jwt = false

[functions.poll-trial-video]
verify_jwt = false

[functions.send-contact]
verify_jwt = false

[functions.temp-reset]
verify_jwt = false

